### ISSUE TITLE
Research AWS DynamoDB

### ISSUE THREAD

**Issue by almgong** [UCLA-BD2K/metaprot#14]
Perhaps when the time comes to deploy Metaprot, we should migrate from MongoDB to DynamoDB.

**Comment by vincekyi** [comment]
Compare MongoDB vs DynamoDB

**Comment by almgong** [comment]
see: https://github.com/derjust/spring-data-dynamodb

**Comment by abineetds** [comment]
Okay will look into it

**Comment by almgong** [comment]
Sufficient Research has been made, and DynamoDB has been integrated with Metaprot on alm-dev: 02f7b10.
