### ISSUE TITLE
Exporting Plot as a high definition PNG, SVG, PDF, etc.

### ISSUE THREAD

**Issue by almgong** [UCLA-BD2K/metaprot#17]
Need to research and implement a high quality image exporter for the plot.

**Comment by almgong** [comment]
For metabolite analysis, this is complete. See 14b54af8af829aa57674e0dc298d0c66783e45ad.

Still needs to be done for pattern recognition.

**Comment by almgong** [comment]
Pattern recognition plot export complete in 98a3af5. However, the axes are bold in the output, perhaps the bounding rectangles for zoom are related to this problem?

**Comment by abineetds** [comment]
Will look into it.
