### ISSUE TITLE
Research Deployment on AWS

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/metaprot#21]

**Comment by almgong** [comment]
Elastic Beanstalk has a preconfigured 2-step deployment of applications that use Tomcat/WAR files.

**Comment by almgong** [comment]
Added a stub setup script for deployment, in need of review + testing. f23e702

**Comment by almgong** [comment]
.ebextensions folder should be placed at root of the project to allow arbitrary pre-deploy scripts to run (installs R, etc.)
