### ISSUE TITLE
Testing Different File Sizes for Pattern Recognition

### ISSUE THREAD

**Issue by vincekyi** [UCLA-BD2K/metaprot#27]
Running the tests; running Howards different file sizes

**Comment by almgong** [comment]
DynamoDB has a item size restriction of 400KB. This means that with larger files -> larger results, we will need to either: store result files to S3 (easier, but less efficient with PR tasks that dynamically update the results), or implement some form of chunking. 

Chunking is a bit more complex, but allows us to keep the data access primarily at the database level.
